#pragma once

#include <vector>
#include "codegen_error.hh"
#include "ecsact/entt/detail/registry.hh"
#include "ecsact/entt/detail/assoc_fields_hash.hh"
#include "ecsact/entt/detail/codegen_error.hh"

namespace ecsact::entt::detail {

template<typename C>
struct multi_assoc_storage {
	std::vector<assoc_hash_value_t> storage_hash_value_ids;

	auto ensure(assoc_hash_value_t id) -> void {
		if(std::ranges::find(storage_hash_value_ids, id) ==
			 storage_hash_value_ids.end()) {
			storage_hash_value_ids.emplace_back(id);
		}
	}

	auto erase(assoc_hash_value_t id) -> void {
		auto itr = std::ranges::find(storage_hash_value_ids, id);
		if(itr != storage_hash_value_ids.end()) {
			storage_hash_value_ids.erase(itr);
		}
	}
};

template<typename C>
auto update_indexed_storage(ecsact::entt::registry_t& registry) -> void {
	static_assert(detail::unimplemented_by_codegen<C>, R"(
 -----------------------------------------------------------------------------
| (!) CODEGEN ERROR                                                           |
| `update_indexed_storage<>` template specialization cannot be found. This is |
| typically generated by ecsact_rt_entt_codegen.                              |
 -----------------------------------------------------------------------------
)");
}
} // namespace ecsact::entt::detail
