# This file is maintained by ecsact-dev/ecsact_common
# If changes are required please make them there

name: pr

on:
  pull_request:

jobs:
  typos-check:
    name: Typos Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crate-ci/typos@v1.19.0

  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jidicula/clang-format-action@v4.11.0
        with: { clang-format-version: "18" }
